export const REGISTERSCREEN = 'REGISTERSCREEN';
export const COUNTRY_LIST_SCREEN = 'COUNTRY_LIST_SCREEN';
export const RECENTCHATSCREEN = 'RECENTCHATSCREEN';
export const CHATSCREEN = 'CHATSCREEN';
export const USERS_LIST_SCREEN = 'USERS_LIST_SCREEN';
export const ARCHIVED_SCREEN = 'ARCHIVED_SCREEN';
export const GROUP_STACK = 'GROUP_STACK';
// CONVERSATION_STACK
export const CONVERSATION_STACK = 'CONVERSATION_STACK';
export const CONVERSATION_SCREEN = 'CONVERSATION_SCREEN';
export const USER_INFO = 'USER_INFO';
export const MESSAGE_INFO_SCREEN = 'MESSAGE_INFO_SCREEN';
export const GALLERY_FOLDER_SCREEN = 'GALLERY_FOLDER_SCREEN';
export const GALLERY_PHOTOS_SCREEN = 'GALLERY_PHOTOS_SCREEN';
export const MEDIA_PRE_VIEW_SCREEN = 'MEDIA_PRE_VIEW_SCREEN';
export const CAMERA_SCREEN = 'CAMERA_SCREEN';
export const VIDEO_PLAYER_SCREEN = 'VIDEO_PLAYER_SCREEN';
export const MOBILE_CONTACT_LIST_SCREEN = 'MOBILE_CONTACT_LIST_SCREEN';
export const MOBILE_CONTACT_PREVIEW_SCREEN = 'MOBILE_CONTACT_PREVIEW_SCREEN';
export const MEDIA_POST_PRE_VIEW_SCREEN = 'MEDIA_POST_PRE_VIEW_SCREEN';
export const VIEWALLMEDIA = 'VIEWALLMEDIA';
export const EDITNAME = 'EDITNAME';
export const IMAGEVIEW = 'IMAGEVIEW';
// SETTTING STACK
export const SETTINGS_STACK = 'SETTINGS_STACK';
export const MENU_SCREEN = 'MENU_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const CHATS_CREEN = 'CHATS_CREEN';

// GROUP STACK
export const NEW_GROUP = 'NEW_GROUPF';
export const GROUP_INFO = 'GROUP_INFO';
export const screenConstans = {
   SETTINGS_STACK: 'SETTINGS_STACK',
};
