# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

desc "Cleans Build, Generate IPA for QA: Enterprise, Upload IPA to Firebase with QA Release Notes and distributes to testers, Move IPA to Artifact folder"
lane :qa_firebase do
	clean_build_artifacts
	build_app(scheme: "mirrorfly_rn",
	    workspace: "mirrorfly_rn.xcworkspace",
	    export_options: "JenkinsPlist/MirrorFlyQa.plist",
 	    export_method: "enterprise"

	)
	firebase_app_distribution(
		app: "1:695832127329:ios:f8b6b0fab296a800",
		groups: "reactnative",
      release_notes: "React-Native ios build for bug-fixes: MRN-559,MRN-560,MRN-561,MRN-572,MRN-577,MRN-580,MRN-562,MRN-563,MRN-564,MRN-565,MRN-566,MRN-567,MRN-576,MRN-584,MRN-585,MRN-587,MRN-588,MRN-525,MRN-535,MRN-554,MRN-551,MRN-534,MRN-537,MRN-549,MRN-547,MRN-540,MRN-542,MRN-556",
		firebase_cli_path: "/usr/local/bin/firebase",
		firebase_cli_token: "1//0g53oUKW5j5bJCgYIARAAGBASNwF-L9Ir7Ei_6NzWEsyHOMMXytlesfgXShhLeJWRwbcf2MC3e7BaC5dwYlUZB-_osuQFsxy0Du0"
	)
	IPA_LOCATION = "#{lane_context[SharedValues::IPA_OUTPUT_PATH]}" 
	copy_artifacts(
   		artifacts: [IPA_LOCATION],
		keep_original: false
	)
end
end