# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

desc "Cleans Build, Generate IPA for QA: Enterprise, Upload IPA to Firebase with QA Release Notes and distributes to testers, Move IPA to Artifact folder"
lane :qa_firebase do
	clean_build_artifacts
	build_app(scheme: "mirrorfly_rn",
	    workspace: "mirrorfly_rn.xcworkspace",
	    export_options: "JenkinsPlist/MirrorFlyQa.plist",
 	    export_method: "enterprise"

	)
	firebase_app_distribution(
		app: "1:695832127329:ios:f8b6b0fab296a800",
		groups: "reactnative",
		release_notes: "React-Native ios build for bugfixes MRN-92, MRN-133, MRN-149, MRN-160, MRN-169, MRN-171, MRN-172, MRN-173, MRN-177, MRN-178, MRN-180, MRN-183, MRN-184, MRN-185, MRN-187, MRN-191, MRN-192, MRN-193, MRN-194, MRN-195, MRN-196, MRN-201, MRN-220, MRN-222, MRN-225, MRN-227, MRN-230, MRN-237, MRN-239, MRN-242, MRN-243, MRN-246, MRN-260, MRN-261, MRN-264, MRN-285, MRN-286, MRN-297, MRN-298, MRN-299, MRN-300, MRN-301, MRN-302, MRN-303, MRN-306, MRN-307, MRN-310, MRN-311",
		firebase_cli_path: "/usr/local/bin/firebase",
		firebase_cli_token: "1//0g53oUKW5j5bJCgYIARAAGBASNwF-L9Ir7Ei_6NzWEsyHOMMXytlesfgXShhLeJWRwbcf2MC3e7BaC5dwYlUZB-_osuQFsxy0Du0"
	)
	IPA_LOCATION = "#{lane_context[SharedValues::IPA_OUTPUT_PATH]}" 
	copy_artifacts(
   		artifacts: [IPA_LOCATION],
		keep_original: false
	)
end
end