const config = {
   attachement: true,
   videoDuaration: 40,
   audioDuaration: 60,
   fileSize: 50,
   imageFileSize: 10,
   videoFileSize: 30,
   audioFileSize: 30,
   documentFileSize: 20,
   maxAllowedMediaCount: 5,
   maximumAllowedUsersToForward: 5,
   maximumCharForwardPopUp: 60,
   internetErrorMessage: 'Please check your Internet connection',
   reportMembers: 5,
   GOOGLE_LOCATION_API_KEY: '************',
   typingStatusGoneWaitTime: 500,
   API_URL: '*************',
   licenseKey: '**********',
};
export default config;
