# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload debug qa version to distributes in firebase"
    lane :deploy_qa_debug do
      gradle(task: "clean assembleDebug")
      firebase_app_distribution(
        app: "1:235373697524:android:8b3becf8d8ff9be3a0c1a1",
        groups: "reactnative",
        release_notes: "React-Native android 1.2.3",
        apk_path: "../android/app/build/outputs/apk/debug/app-debug.apk",
        
        firebase_cli_token: "1//0gfTJ_oWJ0mHNCgYIARAAGBASNwF-L9IrYZM4cUIV5EB8gVnSvtMC6Q7aAtgrgG8R1ybhSY1Np_5r5UuZu28N144_weOQDyONcW4",
      )
    end

    desc "Upload release qa version to distributes in firebase"
    lane :deploy_qa_release do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
        app: "1:235373697524:android:8b3becf8d8ff9be3a0c1a1",
        groups: "reactnative",
        release_notes: "React-Native android build for bugfix - MRN-670,MRN-669,MRN-664,MRN-659,MRN-646,MRN-642,MRN-637,MRN-636,MRN-634,MRN-633,MRN-632,MRN-631,MRN-630,MRN-622,MRN-621,MRN-602,MRN-574,MRN-573,",
        apk_path: "../android/app/build/outputs/apk/release/app-release.apk",
        
        firebase_cli_token: "1//0gfTJ_oWJ0mHNCgYIARAAGBASNwF-L9IrYZM4cUIV5EB8gVnSvtMC6Q7aAtgrgG8R1ybhSY1Np_5r5UuZu28N144_weOQDyONcW4",
      )
    end

end
