# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload debug qa version to distributes in firebase"
    lane :deploy_qa_debug do
      gradle(task: "clean assembleDebug")
      firebase_app_distribution(
        app: "1:235373697524:android:8b3becf8d8ff9be3a0c1a1",
        groups: "reactnative",
        release_notes: "React-Native android 1.2.3",
        apk_path: "../android/app/build/outputs/apk/debug/app-debug.apk",
        
        firebase_cli_token: "1//0gfTJ_oWJ0mHNCgYIARAAGBASNwF-L9IrYZM4cUIV5EB8gVnSvtMC6Q7aAtgrgG8R1ybhSY1Np_5r5UuZu28N144_weOQDyONcW4",
      )
    end

    desc "Upload release qa version to distributes in firebase"
    lane :deploy_qa_release do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
        app: "1:235373697524:android:8b3becf8d8ff9be3a0c1a1",
        groups: "reactnative",
        release_notes: "React-Native android build for bugfix - MRN-647, MRN-671, MRN-635, MRN-629 MRN-662, MRN-661, MRN-649, MRN-645, MRN-610, MRN-609, MRN-606, MRN-597, MRN-596, MRN-595, MRN-593, MRN-592, MRN-591, MRN-554, MRN-527, MRN-524, MRN-523, MRN-522",
        apk_path: "../android/app/build/outputs/apk/release/app-release.apk",
        
        firebase_cli_token: "1//0gfTJ_oWJ0mHNCgYIARAAGBASNwF-L9IrYZM4cUIV5EB8gVnSvtMC6Q7aAtgrgG8R1ybhSY1Np_5r5UuZu28N144_weOQDyONcW4",
      )
    end

end
